BufeteBundle\Entity\Revisiones:
    type: entity
    table: revisiones
    indexes:
        IX_Relationship23:
            columns:
                - Id_Caso
    id:
        idRevision:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Revision
            generator:
                strategy: IDENTITY
    fields:
        idPersona:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Id_Persona
        tituloEntrega:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: Titulo_Entrega
        fechaCreacion:
            type: datetime
            nullable: false
            column: Fecha_Creacion
        nombreArchivo:
            type: string
            nullable: true
            length: 75
            options:
                fixed: false
            column: Nombre_Archivo
        rutaArchivo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: Ruta_Archivo
        fechaLimite:
            type: datetime
            nullable: true
            column: Fecha_Limite
        comentarios:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: Comentarios
        fechaEnvio:
            type: datetime
            nullable: true
            column: Fecha_Envio
        estadoRevision:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Estado_Revision
    manyToOne:
        idCaso:
            targetEntity: Casos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                Id_Caso:
                    referencedColumnName: Id_Caso
            orphanRemoval: false
    lifecycleCallbacks: {  }
