# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    locale: nl
#    parameter_name: value

services:
    app.autocont:
        class: BufeteBundle\Services\Autocont
        arguments: ["null"]

    app.registrocunoc:
        class: BufeteBundle\Services\Registrocunoc
        arguments: ['carne']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.security.access_denied_handler:
        class: BufeteBundle\Security\AccessDeniedHandler

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
