asignacionclinica_index:
    path:     /
    defaults: { _controller: "BufeteBundle:Asignacionclinica:index" }
    methods:  GET

asignacionclinica_asesor:
    path:     /ClinicasAsesor
    defaults: { _controller: "BufeteBundle:Asignacionclinica:clinicasAsesor" }
    methods:  GET

asignacionclinica_show:
    path:     /{idAsignacion}/show
    defaults: { _controller: "BufeteBundle:Asignacionclinica:show" }
    methods:  GET

asignacionclinica_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Asignacionclinica:new" }
    methods:  [GET, POST]

asignacionclinica_edit:
    path:     /{idAsignacion}/edit
    defaults: { _controller: "BufeteBundle:Asignacionclinica:edit" }
    methods:  [GET, POST]

asignacionclinica_delete:
    path:     /{idAsignacion}/delete
    defaults: { _controller: "BufeteBundle:Asignacionclinica:delete" }
    methods:  DELETE

asignacionclinica_listEstudiantes:
    path:     /{idAsignacion}/listEstudiantes
    defaults: { _controller: "BufeteBundle:Asignacionclinica:listEstudiantes" }
    methods:  GET

asignacionclinica_printlistaEstudiantes:
    path:     /{idAsignacion}/printlistaEstudiantes
    defaults: { _controller: "BufeteBundle:Asignacionclinica:printlistaEstudiantes" }
    methods:  GET

asignacionclinica_printnotaEstudiantes:
    path:     /{idAsignacion}/printnotaEstudiantes
    defaults: { _controller: "BufeteBundle:Asignacionclinica:printnotaEstudiantes" }
    methods:  GET

asignacionclinica_listClinicasEstAsesor:
    path:     /{idAsignacion}/ListClinicasEstAsesor
    defaults: { _controller: "BufeteBundle:Asignacionclinica:ListClinicasEstAsesor" }
    methods:  [GET, POST]

asignacionclinica_editNota:
    path:     /{idAsignacion}/asignarNota
    defaults: { _controller: "BufeteBundle:Asignacionclinica:editNota" }
    methods:  [GET, POST]

asignacionclinica_listClinicasEst:
    path:     /ListClinicasEst
    defaults: { _controller: "BufeteBundle:Asignacionclinica:ListClinicasEst" }
    methods:  GET
