demandantes_index:
    path:     /index
    defaults: { _controller: "BufeteBundle:Demandantes:index" }
    methods:  GET

demandantes_show:
    path:     /{idDemandante}/show
    defaults: { _controller: "BufeteBundle:Demandantes:show" }
    methods:  GET

demandantes_new:
    path:     /new
    defaults: { _controller: "BufeteBundle:Demandantes:new" }
    methods:  [GET, POST]

demandantesecre_new:
    path:     /newdemandante
    defaults: { _controller: "BufeteBundle:Demandantes:demandantesecre" }
    methods:  [GET, POST]

demandantes_edit:
    path:     /{idDemandante}/edit
    defaults: { _controller: "BufeteBundle:Demandantes:edit" }
    methods:  [GET, POST]

demandantesecre_edit:
    path:     /{idDemandante}/editar
    defaults: { _controller: "BufeteBundle:Demandantes:editdemandante" }
    methods:  [GET, POST]

demandantes_delete:
    path:     /{idDemandante}/delete
    defaults: { _controller: "BufeteBundle:Demandantes:delete" }
    methods:  DELETE
